spring.application.name=Event Management System - Kernel
spring.security.user.name=user
spring.security.user.password=pass
spring.datasource.driverClassName=org.h2.Driver

kola.event.management.folder.event.images=~/.kola/events/photo/
kola.event.management.folder.eventspot.images=~/.kola/events/spots/photo/
